# Parte 1 – Visualización con Plotly

Responsable: Lucia Pulido

#### Paso 1: Cargar el dataset en assignment_3/datos/. Leerlo con pd.read_csv (si tiene ubigeos, conservarlos como texto). Mostrar sus dimensiones y las primeras 5 filas.

In [ ]:
import pandas as pd

df = pd.read_csv("datos/dataset.csv", dtype=str)

print("Dimensiones del dataset:", df.shape)

display(df.head())

Dimensiones del dataset: (25, 9)

,ubigeo,departamento,declaratorias,prorrogas,capital,latitud,longitud,lluvia_total_mm,dias_lluvia_fuerte
0,01,Amazonas,1,0,Chachapoyas,-6.23169,-77.86903,436.5,1
1,02,Áncash,0,0,Huaraz,-9.52614,-77.52869,975.3,7
2,03,Apurímac,0,0,Abancay,-13.63426,-72.8838,711.8,2
3,04,Arequipa,0,0,Arequipa,-16.39899,-71.53747,189.9,0
4,05,Ayacucho,1,0,Ayacucho,-13.1638,-74.22345,485.1,0

#### Paso 2: Indicar qué tema o pregunta se abordará y qué columnas se usarán.

## Objetivo del análisis

Se analizará la distribución territorial de las lluvias y los decretos de emergencia por departamento. Se busca identificar diferencias entre departamentos y explorar la posible relación entre las variables relacionadas con las lluvias y las emergencias.

Para ello, se utilizarán las variables disponibles en el dataset, considerando el departamento como unidad de análisis y las columnas que permitan medir las lluvias y los decretos de emergencia.

In [2]:
print("Columnas disponibles:")
print(df.columns.tolist())

print("\nTipos de datos:")
print(df.dtypes)

display(df.head())

Columnas disponibles:
['ubigeo', 'departamento', 'declaratorias', 'prorrogas', 'capital', 'latitud', 'longitud', 'lluvia_total_mm', 'dias_lluvia_fuerte']

Tipos de datos:
ubigeo                str
departamento          str
declaratorias         str
prorrogas             str
capital               str
latitud               str
longitud              str
lluvia_total_mm       str
dias_lluvia_fuerte    str
dtype: object

,ubigeo,departamento,declaratorias,prorrogas,capital,latitud,longitud,lluvia_total_mm,dias_lluvia_fuerte
0,01,Amazonas,1,0,Chachapoyas,-6.23169,-77.86903,436.5,1
1,02,Áncash,0,0,Huaraz,-9.52614,-77.52869,975.3,7
2,03,Apurímac,0,0,Abancay,-13.63426,-72.8838,711.8,2
3,04,Arequipa,0,0,Arequipa,-16.39899,-71.53747,189.9,0
4,05,Ayacucho,1,0,Ayacucho,-13.1638,-74.22345,485.1,0

### Paso 3. Crear un gráfico interactivo de barras con Plotly Express

In [3]:
%pip install plotly

import plotly.express as px

Requirement already satisfied: plotly in /opt/anaconda3/lib/python3.14/site-packages (6.7.0)
Requirement already satisfied: narwhals>=1.15.1 in /opt/anaconda3/lib/python3.14/site-packages (from plotly) (2.23.0)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.14/site-packages (from plotly) (26.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:

col_departamento = "departamento"

decretos = (
    df.groupby(col_departamento)
    .size()
    .reset_index(name="cantidad_decretos")
    .sort_values("cantidad_decretos", ascending=False)
)

fig_barras = px.bar(
    decretos,
    x=col_departamento,
    y="cantidad_decretos",
    title="Cantidad de registros por departamento",
    labels={
        col_departamento: "Departamento",
        "cantidad_decretos": "Cantidad de registros"
    }
)

fig_barras.show()

### Paso 4. Crear un gráfico interactivo de dispersión

In [6]:

import plotly.express as px

fig_dispersion = px.scatter(
    df,
    x="lluvia_total_mm",
    y="dias_lluvia_fuerte",
    hover_name="departamento",
    title="Relación entre lluvia total y días de lluvia fuerte",
    labels={
        "lluvia_total_mm": "Lluvia total (mm)",
        "dias_lluvia_fuerte": "Días de lluvia fuerte",
        "departamento": "Departamento"
    }
)

fig_dispersion.show()

### Paso 5. Exportar el gráfico interactivo a HTML

In [ ]:
fig_dispersion.write_html("grafico.html")
print("Gráfico exportado correctamente")

Gráfico exportado correctamente

In [8]:
fig_barras.write_html("grafico_barras.html")
fig_dispersion.write_html("grafico_dispersion.html")